### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by Catwhynot-Dev** [nenge123/vba_next_wasm#2]
1，建议搞个0.5，2，4，8倍速（加速游戏非常不明显）
2，2，4倍柔化有bug，两个一起用成了八（还是六）倍柔化
3，信息下载有bug
![Screenshot 2022-02-05 5 37 58 PM](https://user-images.githubusercontent.com/94798292/152661307-b0e2f263-da8c-40c9-b669-e3edd01b0f47.png)
4，画面继续是啥玩意
5，开始界面有两个添加游戏和vbanext-wasm.7z为运行核心文件,不可删除!如果出现奇异问题可以尝试删除!
6，没了。。模拟器很不错，继续加油！:)

**Comment by nenge123** [comment]
尽可能不要直接对比原生应用。因为两者之间某极大性能区别。

加速问题
网页并非你想象中那么随意的，javascript,它是单线程，计时器是有极限值的，不存在八倍速四倍速。另外音频是独立的会因为速度不一致会产生卡顿，崩溃。所以这方面目前不会尝试调整。

信息下载不是bug，只不过是计划中的功能，他实际上是查看list.html的内容。


两个两个上传也不是问题，只不过是为了方便。

画面继续不是什么玩意，是为了防止某些操作意外停止计数器，参考加速问题。
