### ISSUE TITLE
[BUG]导致游戏丢档

### ISSUE THREAD

**Issue by potato616** [nenge123/vba_next_wasm#3]
大佬，文件处理/重设里面的音乐和刷新点了会导致存档丢失

**Comment by nenge123** [comment]
这个很正常，已经反复强调不会自动保存，因为你没保存就刷新了。

你要习惯闲的蛋疼的时候按一下即存.

git 越来越难访问了  以后有什么问题去这里 https://nenge.net/emulator/app/emujs/
