### ISSUE TITLE
skyemu

### ISSUE THREAD

**Issue by zelongzheng** [nenge123/vba_next_wasm#7]
skyemu我试了, 很多rom在移动端上面有很严重的bug, 人物会突然间乱码音乐突然中断 ,对移动端兼容性不好 ,你这个好很多

**Comment by nenge123** [comment]
skyemu现在是v3測試版，修复了很多。它代码里面还支持nds（实际上手机运行不了，）

你可以去这里看看dqm.nenge.net
这个仓库的js太旧了，我现在用的js自己写了个indexdb，集成zip 7z rar等解压。


手机端兼容问题，主要是声音问题，离开一段时间声音从running变成停止，主要用户事件激活，这就导致对象异常，不停的异常导致页面卡顿，甚至崩溃。
